<a href="https://colab.research.google.com/github/Hubertmeteor/Breast-cancer-prediction-using-Deep-Learning/blob/main/Breast_Cancer_prediction_using_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing Necessaory Models for Deep Learning**

Imports the main PyTorch library.......**import torch**

Imports the neural network module from PyTorch, which provides tools for building neural networks..........**import torch.nn as nn**


 Imports the optimization module from PyTorch, which provides various optimization algorithms for training neural networks.......**import torch.optim as optim**

Imports the load_breast_cancer function from scikit-learn, which allows you to load the Breast Cancer Wisconsin dataset........**from sklearn.datasets import load_breast_cancer**

Imports the train_test_split function from scikit-learn, which allows you to split datasets into training and testing subsets.......**from sklearn.model_selection import train_test_split**


Imports the StandardScaler class from scikit-learn, which allows you to standardize features by removing the mean and scaling to unit variance.......**from sklearn.preprocessing import StandardScaler**




In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.datasets import load_iris
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


**Device Configuration Testing**

In [ ]:
device=torch.device("cuda" if torch.cuda.is_available()else "cpu")
print(f"Using device:{device}")

Using device:cuda


**Data Collection and preprocessing**

In [ ]:
data=load_breast_cancer()
X=data.data
y=data.target

In [ ]:
print(X)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [ ]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [ ]:
print(y[:5])

[0 0 0 0 0]


In [ ]:
#Data splited as training dataset(80%) and test dataset (20%)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
print(X.shape)
print(X_train.shape)
print(X_test.shape)

(569, 30)
(455, 30)
(114, 30)


This preprocessing step is commonly used in machine learning workflows to scale features such that they have zero mean and unit variance, which can help improve the performance of many machine learning algorithms.

In [ ]:
scaler=StandardScaler()                   #This instance will be used to scale the features of your dataset.
X_train=scaler.fit_transform(X_train)     #the mean and standard deviation of the training data will be computed and used to scale the features.
X_test=scaler.transform(X_test)           #fitted to the training data to transform the test data (X_test).
                                          #This ensures that the same scaling is applied to both the training and test data.

In [ ]:
type(X_train)

numpy.ndarray

Prepares the data for training and testing with PyTorch models. Make sure that the device variable is properly defined, typically either as "cuda" for GPU or "cpu" for CPU, before executing these lines.

In [ ]:
X_train=torch.tensor(X_train,dtype=torch.float32).to(device)
y_train=torch.tensor(y_train,dtype=torch.float32).to(device)
X_test=torch.tensor(X_test,dtype=torch.float32).to(device)
y_test=torch.tensor(y_test,dtype=torch.float32).to(device)

**Neural Network Architecture**

In [ ]:
class NeuralNet(nn.Module):
  def __init__(self,input_size,hidden_size,output_size):  #method initializes the neural network layers
    super(NeuralNet,self).__init__()                      #defines a fully connected layer
    self.fc1=nn.Linear(input_size,hidden_size)            #fc1--->fully Connected layer one
    self.relu=nn.ReLU()                                   #creates a rectified linear unit activation function, commonly known as ReLU.
    self.fc2=nn.Linear(hidden_size,output_size)           ##fc2--->fully Connected layer second
    self.sigmoid=nn.Sigmoid()                             #creates a sigmoid activation function, typically used for binary classification problems to squash the output into the range [0, 1].

  def forward(self,x):
    out=self.fc1(x)           #Passes the input x through the first fully connected layer (fc1).
    out=self.relu(out)        #Applies the rectified linear unit activation function (relu) to the output of the first layer.
    out=self.fc2(out)         #Passes the output of the first layer through the second fully connected layer (fc2).
    out=self.sigmoid(out)     #Applies the sigmoid activation function (sigmoid) to the output of the second layer.
                              #This is typically used when the network is used for binary classification tasks.
    return out


**Set Hyperparameters**

In [ ]:
input_size=X_train.shape[1]
hidden_size=64
output_size=1
learning_rate=0.001
num_epoches=100

In [ ]:
#creating an instance of the NeuralNet class, passing the parameters input_size, hidden_size, and output_size, and then moving the model to the specified device using .to(device)
model=NeuralNet(input_size,hidden_size,output_size).to(device)


This line creates an instance of the binary cross-entropy loss function (BCELoss) from PyTorch's nn module. BCELoss is commonly used for binary classification problems. It measures the binary cross-entropy between the target and the output.

Adam is an adaptive learning rate optimization algorithm that is well-suited for training deep neural networks. It updates the parameters (weights) of the model based on the gradients of the loss function with respect to those parameters. Here, you're passing model.parameters() to specify which parameters of the model should be optimized, and lr=learning_rate sets the learning rate for the optimizer to the value you defined earlier.

In [ ]:
criterion=nn.BCELoss()
optimzer=optim.Adam(model.parameters(),lr=learning_rate)


**Training the Neural network**


**for epoch in range(num_epoches)::** This loop iterates over the specified number of epochs (num_epoches), allowing the model to train for multiple passes over the entire dataset.

**model.train()::** This sets the model to training mode. This is necessary because some layers may behave differently during training (e.g., dropout layers).

**optimizer.zero_grad()::** This clears the gradients of all optimized tensors. Gradients accumulate by default, so it's necessary to clear them before each optimization step.

Forward Pass:

**outputs = model(X_train)::** Passes the input data (X_train) through the model to get the predicted outputs.
loss = criterion(outputs, y_train.view(-1, 1)): Computes the loss using the criterion (loss function), comparing the predicted outputs (outputs) with the actual labels (y_train).
Backward Pass and Optimization:

**loss.backward():: **Computes gradients of the loss with respect to the model parameters (backpropagation).
**optimizer.step()::** Updates the model parameters based on the computed gradients (optimization step).
Evaluation:

**with torch.no_grad()::** This block ensures that gradients are not computed for operations inside it. This is necessary because we are only evaluating the model's performance and not updating parameters.
predicted = outputs.round():: Rounds the predicted outputs to get binary predictions (0 or 1).
**correct = (predicted == y_train.view(-1, 1)).float().sum()::** Computes the number of correct predictions by comparing the predicted labels with the actual labels.
**accuracy = correct / y_train.size(0)::** Computes the accuracy by dividing the number of correct predictions by the total number of training examples.

In [ ]:

for epoch in range(num_epoches):
  model.train()
  optimzer.zero_grad()
  outputs=model(X_train)
  loss=criterion(outputs,y_train.view(-1,1))
  loss.backward()
  optimzer.step()

  with torch.no_grad():
    predicted=outputs.round()
    correct=(predicted==y_train.view(-1,1)).float().sum()
    accuracy=correct/y_train.size(0)

  if (epoch+1)%10==0:
    print(f"Epoch[{epoch+1}/{num_epoches}],Loss:{loss.item():.4f},Accuracy:{accuracy.item()*100:.2f}%")

Epoch[10/100],Loss:0.5700,Accuracy:81.32%
Epoch[20/100],Loss:0.4481,Accuracy:88.57%
Epoch[30/100],Loss:0.3541,Accuracy:91.65%
Epoch[40/100],Loss:0.2830,Accuracy:93.41%
Epoch[50/100],Loss:0.2311,Accuracy:95.16%
Epoch[60/100],Loss:0.1937,Accuracy:96.26%
Epoch[70/100],Loss:0.1668,Accuracy:96.70%
Epoch[80/100],Loss:0.1470,Accuracy:97.14%
Epoch[90/100],Loss:0.1320,Accuracy:97.14%
Epoch[100/100],Loss:0.1202,Accuracy:97.36%


**Model Evaluation**

Training data set and Testing data set

In [ ]:
model.eval()
with torch.no_grad():
  outputs=model(X_train)
  predicted=outputs.round()
  correct=(predicted==y_train.view(-1,1)).float().sum()
  accuracy=correct/y_train.size(0)
print(f"Accuracy on training  data: {accuracy.item()*100:.2f}%")


Accuracy on training  data: 97.58%


In [ ]:
model.eval()
with torch.no_grad():
  outputs=model(X_test)
  predicted=outputs.round()
  correct=(predicted==y_test.view(-1,1)).float().sum()
  accuracy=correct/y_test.size(0)
print(f"Accuracy on test  data: {accuracy.item()*100:.2f}%")

Accuracy on test  data: 96.49%
